# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goal < Formula
  desc "The Go-AL formula"
  homepage "https://github.com/mas2020-golang/homebrew-goal"
  version "0.6.0-dev1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/mas2020-golang/goal/releases/download/v0.6.0-dev1/goal_0.6.0-dev1_Darwin-x86_64.tar.gz"
    sha256 "6b2237de9efebbb04c16d1a1e9c1f5647049fc2e4e12a3f6698025a5e94489c4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mas2020-golang/goal/releases/download/v0.6.0-dev1/goal_0.6.0-dev1_Linux-x86_64.tar.gz"
    sha256 "3e2d45530053c4b74796d67b7261ce77e7dc92257df23f20a9bd48b47d270cc7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mas2020-golang/goal/releases/download/v0.6.0-dev1/goal_0.6.0-dev1_Linux-arm64.tar.gz"
    sha256 "5096c0bb4daf0a921e7b1fbc7a6a5d470213ea6fe072aacb4b81fdf5ba43e8e9"
  end

  def install
    bin.install "goal"
  end
end
