# This file was generated by GoReleaser. DO NOT EDIT.
class Goal < Formula
  desc "The Go-AL formula"
  homepage "https://github.com/mas2020-golang/homebrew-goal"
  version "0.6.0-dev1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mas2020-golang/goal/releases/download/v0.6.0-dev1/goal_0.6.0-dev1_Darwin-x86_64.tar.gz"
    sha256 "43fd80f03d55c4d7f9ae0fb8663853dc58a3dde0e81c292b0fd80b7ddfbe685d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mas2020-golang/goal/releases/download/v0.6.0-dev1/goal_0.6.0-dev1_Linux-x86_64.tar.gz"
    sha256 "c0c57a45f40685659ad66d16966b18ac2981f9a9f894c3e000d39bc20fcabb04"
  end

  def install
    bin.install "goal"
  end
end
